add

diff --git a/Homework/02.OS_Security/M04-U08/TASK#01/task01 b/Homework/02.OS_Security/M04-U08/TASK#01/task01
--- a/Homework/02.OS_Security/M04-U08/TASK#01/task01
+++ b/Homework/02.OS_Security/M04-U08/TASK#01/task01
@@ -3,7 +3,7 @@
 ############################| TASK#01 |#############################
 #                           DESCRIPTION
 #        Add Backports Repository (for Ubuntu based systems)
-#                   Install Apache2, Python, SSH
+#                  Install Apache2, Python, SSH, FTP
 #-------------------------------------------------------------------
 #               Written by Yuriy Shamray (aka Prospero)
 #                           MIFIIB - 2023
@@ -211,7 +211,7 @@ then
 else
     echo "${red} ${icon_ko} Inactive (stopped) ${nocolor}"
     sleep 2
-    echo "\n${cyan}${icon_wait} Starting SSH Service Status ${nocolor}"
+    echo "\n${cyan}${icon_wait} Starting SSH Service ${nocolor}"
     sleep 2
     sudo systemctl start ssh 1>/dev/null && echo "${green}${icon_ok} Done! ${nocolor}"
 fi
@@ -221,6 +221,70 @@ sleep 2
 echo "\n${cyan}${icon_wait} Adding Rules to UFW ${icon_arrowr} 'SSH' ${nocolor}"
 sleep 2
 sudo ufw allow 2222
+sleep 2
+sudo ufw status numbered
+echo "${green}${icon_ok} Done! ${nocolor}"
+
+####################################################################
+############################| STAGE#06 |############################
+# Install & Setup FTP
+sleep 2
+echo "\n${purple}[${icon_stage} STAGE#06] - ${cyan}${icon_wait} Checking VSFTPD (Very Secure FTP Daemon) ${nocolor}\n"
+sleep 2
+if ! vsftpd -version 2>/dev/null
+then
+    echo -n "${red}${icon_ko} VSFTPD not found!";sleep 2; echo "${cyan} ${icon_wait} Installing VSFTPD ${nocolor}"
+    sleep 2
+    sudo apt install vsftpd -y
+    sudo cp /etc/vsftpd.conf /etc/vsftpd.conf.backup
+    sudo nano /etc/vsftpd.conf
+      anonymous_enable=NO
+      local_enable=YES
+      write_enable=YES
+      write_enable=YES
+      local_umask=022
+      xferlog_enable=YES
+      xferlog_std_format=YES
+      connect_from_port_20=YES
+      chroot_local_user=YES
+      allow_writeable_chroot=YES
+      ssl_enable=YES
+      ssl_tlsv1=YES
+      ssl_sslv2=NO
+      ssl_sslv3=NO
+      rsa_cert_file=/etc/ssl/private/ssl-cert-snakeoil.pem
+      rsa_private_key_file=/etc/sssl_ciphers=HIGHsl/private/ssl-cert-snakeoil.key
+      allow_anon_ssl=NO
+      force_local_data_ssl=YES
+      force_local_logins_ssl=YES
+      ssl_ciphers=HIGH
+      use_localtime=YES
+    sudo service vsftpd restart
+else
+    vsftpd -version
+    echo "${green}${icon_ok} VSFTPD already installed! ${nocolor}"
+fi
+#--------------------------------------------------------------------
+#Check VSFTPD service
+sleep 2
+echo -n "\n${cyan}${icon_wait} Checking SSH Service Status ${nocolor}"
+if systemctl is-active -q vsftpd
+then
+    sleep 2
+    echo "${green} ${icon_ok} Active (running) ${nocolor}"
+else
+    echo "${red} ${icon_ko} Inactive (stopped) ${nocolor}"
+    sleep 2
+    echo "\n${cyan}${icon_wait} Starting VSFTPD Service ${nocolor}"
+    sleep 2
+    sudo systemctl start vsftpd 1>/dev/null && echo "${green}${icon_ok} Done! ${nocolor}"
+fi
+#-------------------------------------------------------------------
+# add UFW rules for VSFTP
+sleep 2
+echo "\n${cyan}${icon_wait} Adding Rules to UFW ${icon_arrowr} VSFTPD ${nocolor}"
+sleep 2
+sudo ufw allow ftp
 sleep 2
 sudo ufw status numbered
 echo "${green}${icon_ok} Done! ${nocolor}"
